---

- name: install icinga2 web packages
  package:
    name: '{{ icinga2_web_packages }}'
    state: present

# Allow httpd to connect to the mysql database
- name: set httpd_can_network_connect_db flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes

# Allow httpd to connect to the network
- name: set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: check if icingaweb2 table and user in mysql exist
  shell: >
    set -o pipefail;
    mysql
    --user={{ icinga2_web_database_root_user }}
    --password={{ icinga2_web_database_root_pass }}
    --host={{ icinga2_web_icingaweb2_database_host }}
    --ssl-ca={{ icinga2_web_ca_path }}
    {{ icinga2_web_icingaweb2_database_name }}
    -e "SHOW TABLES;" | grep "icinga_hosts"
  register: icinga2_web_register_icingaweb2_imported
  changed_when: icinga2_web_register_icingaweb2_imported.rc == 1
  failed_when: "'Access denied for' in icinga2_web_register_icingaweb2_imported.stderr"

- name: import icingaweb2 database schema using the root user
  mysql_db:
    name: '{{ icinga2_web_icingaweb2_database_name }}'
    login_host: '{{ icinga2_web_icingaweb2_database_host }}'
    login_port: '{{ icinga2_web_icingaweb2_database_port }}'
    login_user: '{{ icinga2_web_database_root_user }}'
    login_password: '{{ icinga2_web_database_root_pass }}'
    ssl_ca: '{{ icinga2_web_ca_path }}'
    state: import
    target: /usr/share/doc/icingaweb2/schema/mysql.schema.sql
  run_once: True
  when: icinga2_web_register_icingaweb2_imported.rc == 1

- name: create a user with access only to the icingaweb2 database using the root user
  mysql_user:
    name: '{{ icinga2_web_icingaweb2_database_user }}'
    password: '{{ icinga2_web_icingaweb2_database_pass }}'
    priv: '{{ icinga2_web_icingaweb2_database_name }}.*:ALL'
    login_host: '{{ icinga2_web_icingaweb2_database_host }}'
    login_port: '{{ icinga2_web_icingaweb2_database_port }}'
    login_user: '{{ icinga2_web_database_root_user }}'
    login_password: '{{ icinga2_web_database_root_pass }}'
    ssl_ca: '{{ icinga2_web_ca_path }}'
    state: present
  run_once: True
  when: icinga2_web_register_icingaweb2_imported.rc == 1

- name: ensure icingaweb2 modules directory is present
  file:
    name: /etc/icingaweb2/enabledModules
    state: directory
    owner: root
    group: icingaweb2
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: icingaweb2_config_t
    selevel: s0
  notify: icinga2_web reload icinga2
